adding a json for farmers and minors changes for read and display data
YvesC88/MonMaraicher pull request #5
Opened 2024-03-13 23:53 UTC by YvesC88

I added a JSON for farmers. Don't take the images into account because I haven't made the changes yet.
The tests are also to be checked because they cover part of the business logic

2024-03-14 09:04 UTC, MathisDetourbet requested changes
Good job for the tests. They are simple and easy to understand.

I let you some changes to do. But some are not needed now.

Next time try to split into multiple and smaller PR as possible. Here you are doing different things:
- unit tests vm
- decoding data and add json file
- refactoring of your models

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Features/FarmerDetail/FarmerDetailsTests.swift
> +final class FarmerDetailsTests: XCTestCase {
Important to keep the name of the file/object your are testing. So FarmerDetailsViewModelTests because your are testing the view model nothing more

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Features/Map/MapViewModel.swift
> +    @Published var selectedFarmerPlace: Farmer?
So the naming needs to be updated as well. I would see selectedFarmer

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Features/Map/MapViewModel.swift
> +    @Published var allFarmerPlaces: [Farmer] = []
Same here: allFarmers

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Features/Map/MapViewModel.swift
> +    private func readJsonFarmers() {
Le naming n'est pas mauvais en soi dans le sens où on comprend ce qui est fait cad on lit un json. Mais c'est pas exactement ce qui se passe car on le lit certes mais on décode le json en un objet farmer ici. Mais decodeJsonFarmer n'est pas top non plus dans un view model car un VM ne doit pas avoir cette notion technique. Un view model parle de view et format de la data. La on parle decoding de data.
Je te propose dans une next PR de déplacer ce code dans un autre acteur comme un service par exemple. Et ton VM appellera ce service. Et tu pourras plutôt renommer cette func en par ex "loadFarmers". 

Donc tu peux déjà rename la func et tu feras un service dans une autre PR ;)

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Features/Map/MapViewModel.swift
> +            print("Error decoding: \(error)")
Si y a une erreur on fait quoi côté view ? Comment le user sait qu'il y a eu une erreur ? Ça peut être fait dans une autre PR si tu veux ;)

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Model/Address.swift
> +struct Address: Codable, Hashable {
Check the codable protocol and see why you don't fully need it. You are decoding data only. I let you find the answer ;)

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Model/FarmerPlace/FarmersPlaces.swift
> +struct FarmersPlaces: Codable {
I don't understand the naming here. Why farmer places?

+ Same for codable protocol

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Model/FarmerPlace/FarmersPlaces.swift
> +struct Farmer: Identifiable, Codable, Hashable {
I think the naming is better :) 👍

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Model/Location.swift
> +struct Location: Codable, Hashable {
Same for codable protocol

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Model/FarmerPlace/FarmersPlaces.swift
> +struct Farmer: Identifiable, Codable, Hashable {
Same for codable protocol

2024-03-14 09:04 UTC, MathisDetourbet commented on MonMaraicher/Features/FarmerDetail/FarmerDetailsTests.swift
> +    }
Some unit tests are missing here. For example markerSystemImageName

2024-03-14 09:35 UTC, YvesC88 commented on MonMaraicher/Model/FarmerPlace/FarmersPlaces.swift
> +struct FarmersPlaces: Codable {
In fact, I thought it was correct to comply with the Codable protocol which is Decodable and Encodable but maybe you want to make me understand that in my case, I'm only decoding so Decodable, right?

2024-03-14 09:55 UTC, MathisDetourbet commented on MonMaraicher/Model/FarmerPlace/FarmersPlaces.swift
> +struct FarmersPlaces: Codable {
That's right

2024-03-14 10:39 UTC, YvesC88 commented on MonMaraicher/Features/Map/MapViewModel.swift
> +    private func readJsonFarmers() {
A new PR will be created for this and will therefore be light ;)

2024-03-14 10:41 UTC, YvesC88 commented on MonMaraicher/Features/Map/MapViewModel.swift
> +            print("Error decoding: \(error)")
I take note for another PR and manage the display of the error for the user

2024-03-14 10:51 UTC, MathisDetourbet commented on MonMaraicher/Model/Farmer/Farmers.swift
> +struct Farmers: Decodable {
Does this struct really useful?

2024-03-14 13:08 UTC, YvesC88 commented on MonMaraicher/Model/Farmer/Farmers.swift
> +struct Farmers: Decodable {
Good question ..

2024-03-15 08:56 UTC, MathisDetourbet approved these changes

2024-03-15 08:58 UTC, merged